// ─────────────────────────────────────────────────────────────────────────────
// Shared Scheduling Types — source of truth for all calendar-related data.
// Used by both frontend and replicated in server/services/scheduling.ts for
// the backend (which uses its own copy to avoid Vite/ESM import issues).
// ─────────────────────────────────────────────────────────────────────────────

import type { Timestamp } from 'firebase/firestore';

// ─── Enums ───────────────────────────────────────────────────────────────────

export type EventType =
  | 'availability'
  | 'blocked_time'
  | 'shift_offer'
  | 'booking_request'
  | 'booking_confirmed'
  | 'interview';

export type EventStatus =
  | 'draft'
  | 'available'
  | 'pending'
  | 'offered'
  | 'accepted'
  | 'declined'
  | 'confirmed'
  | 'cancelled'
  | 'completed';

export type UserRole = 'nanny' | 'agency' | 'family' | 'admin';

export type RecurrenceFrequency = 'daily' | 'weekly';

export type EventVisibility = 'private' | 'role_based';

export type UrgencyLevel = 'low' | 'normal' | 'high';

export type EventSource = 'agency_created' | 'family_requested' | 'nanny_availability';

// ─── Recurrence ──────────────────────────────────────────────────────────────

export interface RecurrenceRule {
  enabled: boolean;
  frequency?: RecurrenceFrequency;
  /** Interval between occurrences, e.g. every 2 weeks. Defaults to 1. */
  interval?: number;
  /** ISO day-of-week numbers (0=Sun … 6=Sat) for weekly recurrence. */
  daysOfWeek?: number[];
  /** Stop expanding after this date. */
  endsOn?: Timestamp | null;
  /** Stop expanding after this many occurrences. */
  occurrences?: number | null;
}

// ─── Core ScheduleEvent document shape (Firestore) ───────────────────────────

/**
 * ScheduleEvent — the single document type stored in `schedule_events`.
 *
 * MVP choice: recurring events are EXPANDED INTO CHILD INSTANCES on write.
 * A parent document holds the recurrence rule; each child instance stores
 * `parentEventId` so they can be managed as a group.
 * This keeps queries simple (no on-read expansion) and allows per-instance overrides.
 */
export interface ScheduleEvent {
  id: string; // Firestore doc ID – not stored in document body

  type: EventType;
  title: string;
  description?: string;

  startAt: Timestamp;
  endAt: Timestamp;
  /** IANA timezone, e.g. "America/New_York". */
  timezone: string;

  status: EventStatus;

  createdBy: string;      // userId
  createdByRole: UserRole;

  // ─── Participants ───────────────────────────────────────────────────────────
  nannyId?: string;
  agencyId?: string;
  familyId?: string;
  childId?: string;

  // ─── Location (privacy-gated) ───────────────────────────────────────────────
  /** Always visible, e.g. "Canarsie, Brooklyn". */
  locationGeneral?: string;
  /** Hidden until exactLocationUnlocked === true for the requesting user. */
  locationExact?: string;
  exactLocationUnlocked?: boolean;

  // ─── Notes ─────────────────────────────────────────────────────────────────
  notesInternal?: string; // agency/admin only
  notesVisible?: string;  // visible to all participants

  // ─── Recurrence ────────────────────────────────────────────────────────────
  recurrence?: RecurrenceRule;
  /** Set on child instances generated by a recurring parent. */
  parentEventId?: string;
  /** 0-based index of this instance within the recurrence series. */
  instanceIndex?: number;

  // ─── Visibility ────────────────────────────────────────────────────────────
  visibility: EventVisibility;

  // ─── Metadata ──────────────────────────────────────────────────────────────
  metadata?: {
    payRate?: number;
    currency?: string;
    urgency?: UrgencyLevel;
    source?: EventSource;
  };

  // ─── Reminders ─────────────────────────────────────────────────────────────
  reminderSettings?: {
    enabled: boolean;
    remind24h?: boolean;
    remind2h?: boolean;
    remind30m?: boolean;
  };

  // ─── Audit ─────────────────────────────────────────────────────────────────
  audit: {
    createdAt: Timestamp;
    updatedAt: Timestamp;
    deletedAt?: Timestamp | null;
  };
}

// ─── Availability Template ────────────────────────────────────────────────────

/**
 * Reusable weekly availability pattern for a nanny.
 * Stored in `availability_templates/{nannyId}`.
 * When applied, generates `schedule_events` of type "availability".
 */
export interface AvailabilityTemplate {
  id: string;
  nannyId: string;
  /** Day slots: key = ISO day number (0–6), value = time windows. */
  slots: Record<
    string,
    Array<{ startTime: string; endTime: string }> // "HH:mm" 24-hour
  >;
  timezone: string;
  effectiveFrom: Timestamp;
  effectiveTo?: Timestamp | null;
  audit: {
    createdAt: Timestamp;
    updatedAt: Timestamp;
  };
}

// ─── Notification Job ────────────────────────────────────────────────────────

export type NotificationChannel = 'fcm' | 'email' | 'in_app';
export type NotificationStatus = 'pending' | 'sent' | 'failed' | 'skipped';
export type NotificationTrigger =
  | 'shift_offered'
  | 'offer_accepted'
  | 'offer_declined'
  | 'booking_confirmed'
  | 'booking_cancelled'
  | 'reminder_24h'
  | 'reminder_2h'
  | 'reminder_30m'
  | 'reschedule_requested';

export interface NotificationJob {
  id: string;
  eventId: string;
  trigger: NotificationTrigger;
  recipientUserId: string;
  recipientRole: UserRole;
  channel: NotificationChannel;
  status: NotificationStatus;
  scheduledAt: Timestamp; // when to fire
  sentAt?: Timestamp | null;
  payload: {
    title: string;
    body: string;
    data?: Record<string, string>;
  };
  audit: {
    createdAt: Timestamp;
    updatedAt: Timestamp;
  };
}

// ─── Audit Log ───────────────────────────────────────────────────────────────

export type AuditAction =
  | 'created'
  | 'status_changed'
  | 'rescheduled'
  | 'accepted'
  | 'declined'
  | 'confirmed'
  | 'cancelled'
  | 'completed'
  | 'location_unlocked';

export interface AuditLogEntry {
  id: string;
  eventId: string;
  actorId: string;
  actorRole: UserRole;
  action: AuditAction;
  fromStatus?: EventStatus;
  toStatus?: EventStatus;
  reason?: string;
  timestamp: Timestamp;
}

// ─── Schedule Conflict ───────────────────────────────────────────────────────

export interface ScheduleConflict {
  conflictingEventId: string;
  entityId: string; // nannyId, familyId, etc.
  entityType: 'nanny' | 'family';
  overlapStart: Timestamp;
  overlapEnd: Timestamp;
  message: string;
}

// ─── Frontend DTO (safe serialised shape sent to client) ─────────────────────

/**
 * CalendarEventDTO — what the frontend receives.
 * Internal fields (notesInternal, locationExact if locked) are stripped out.
 */
export interface CalendarEventDTO {
  id: string;
  type: EventType;
  title: string;
  description?: string;
  start: string;   // ISO-8601
  end: string;     // ISO-8601
  timezone: string;
  status: EventStatus;

  locationLabel?: string;          // locationGeneral always
  canViewExactLocation: boolean;
  exactLocation?: string;          // only if canViewExactLocation

  nannyId?: string;
  nannyName?: string;
  nannyCvid?: string;
  nannyUid?: string;
  agencyId?: string;
  familyId?: string;
  childId?: string;

  notesVisible?: string;
  metadata?: {
    payRate?: number;
    currency?: string;
    urgency?: UrgencyLevel;
  };
  reminderSettings?: ScheduleEvent['reminderSettings'];
  recurrence?: RecurrenceRule;
  parentEventId?: string;
  instanceIndex?: number;

  /** Which actions the current user may perform on this event. */
  allowedActions: EventAction[];
  /**
   * FullCalendar-compatible color token (frontend maps this to a hex/class).
   * 'grey' | 'yellow' | 'green' | 'red' | 'blue' | 'teal'
   */
  colorKey: CalendarColorKey;
}

export type EventAction =
  | 'accept'
  | 'decline'
  | 'confirm'
  | 'cancel'
  | 'reschedule'
  | 'complete'
  | 'view_exact_location'
  | 'edit';

export type CalendarColorKey = 'grey' | 'yellow' | 'green' | 'red' | 'blue' | 'teal';

// ─── API Payload types ────────────────────────────────────────────────────────

export interface GetCalendarEventsInput {
  rangeStart: string; // ISO-8601
  rangeEnd: string;   // ISO-8601
  types?: EventType[];
  statuses?: EventStatus[];
}

export interface CreateAvailabilityInput {
  startAt: string;
  endAt: string;
  timezone?: string;
  title?: string;
  recurrence?: Omit<RecurrenceRule, 'enabled'> & { enabled?: boolean };
  reminderSettings?: ScheduleEvent['reminderSettings'];
}

export interface BlockTimeInput {
  startAt: string;
  endAt: string;
  timezone?: string;
  title?: string;
  reason?: string;
  recurrence?: Omit<RecurrenceRule, 'enabled'> & { enabled?: boolean };
}

export interface CreateShiftOfferInput {
  nannyId: string;
  familyId?: string;
  childId?: string;
  startAt: string;
  endAt: string;
  timezone?: string;
  title: string;
  description?: string;
  locationGeneral?: string;
  locationExact?: string;
  notesVisible?: string;
  metadata?: ScheduleEvent['metadata'];
  reminderSettings?: ScheduleEvent['reminderSettings'];
  recurrence?: Omit<RecurrenceRule, 'enabled'> & { enabled?: boolean };
}

export interface CreateBookingRequestInput {
  nannyId?: string;
  agencyId: string;
  childId?: string;
  startAt: string;
  endAt: string;
  timezone?: string;
  title: string;
  description?: string;
  locationGeneral: string;
  locationExact: string;     // stored encrypted / permission-gated
  notesVisible?: string;
  metadata?: ScheduleEvent['metadata'];
  reminderSettings?: ScheduleEvent['reminderSettings'];
}

export interface CreateInterviewInput {
  nannyId: string;
  familyId?: string;
  startAt: string;
  endAt: string;
  timezone?: string;
  title?: string;
  notesVisible?: string;
  locationGeneral?: string;
}

export interface UpdateEventStatusInput {
  eventId: string;
  status: EventStatus;
  reason?: string;
}

export interface RescheduleEventInput {
  eventId: string;
  startAt: string;
  endAt: string;
  reason?: string;
}
